FROM python:3.10

ENV LANG C.UTF-8
ENV LC_ALL C.UTF-8
ENV TZ=Asia/Almaty

ENV PYTHONUNBUFFERED=1
ENV PYTHONDONTWRITEBYTECODE=1

WORKDIR /app

RUN apt-get update && apt-get install -y \
    nano \
    unixodbc \
    unixodbc-dev \
    tdsodbc \
    libreoffice --no-install-recommends \
    freetds-common freetds-bin freetds-dev \
 && rm -rf /var/lib/apt/lists/* \
 && apt-get clean

ADD docker/dev/odbcinst.ini /etc/

# Upgrade pip and install requirements.txt in a single layer to save space
COPY requirements.txt .
RUN pip install --upgrade pip && pip install -r requirements.txt

COPY . .

# Add an entrypoint script
COPY docker/dev/entrypoint.sh /entrypoint.sh
RUN chmod +x /entrypoint.sh

ENTRYPOINT ["/entrypoint.sh"]
