# Generated by Django 3.2.21 on 2023-09-25 14:01

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('driver', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('student', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='route',
            name='children',
            field=models.ManyToManyField(related_name='children', to='student.Student', verbose_name='Дети'),
        ),
        migrations.AddField(
            model_name='route',
            name='driver',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='driver.driver', verbose_name='Водитель'),
        ),
        migrations.AddField(
            model_name='route',
            name='senior',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='Старший'),
        ),
        migrations.AddField(
            model_name='route',
            name='transport',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='driver.transport', verbose_name='Транспорт'),
        ),
        migrations.AddField(
            model_name='historydriver',
            name='driver',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='driver.driver', verbose_name='Водитель'),
        ),
        migrations.AddField(
            model_name='historydriver',
            name='transport',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='driver.transport', verbose_name='Маршрут'),
        ),
    ]
