# Generated by Django 3.2.21 on 2023-09-27 05:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='userinfo',
            name='is_teacher',
            field=models.BooleanField(default=False),
        ),
    ]
