# Generated by Django 3.2.25 on 2025-09-21 21:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('school', '0002_class_teacher'),
        ('user', '0003_auto_20231211_1042'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='school',
            field=models.ManyToManyField(null=True, related_name='school_employees', to='school.School'),
        ),
    ]
