# Generated by Django 3.2.25 on 2025-10-02 09:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0004_alter_user_school'),
    ]

    operations = [
        migrations.AddField(
            model_name='userinfo',
            name='campus_id',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='userinfo',
            name='subdivision_id',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
