# Generated by Django 3.2.25 on 2025-10-03 06:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0005_auto_20251002_1409'),
    ]

    operations = [
        migrations.RenameField(
            model_name='userinfo',
            old_name='campus_id',
            new_name='level',
        ),
        migrations.RemoveField(
            model_name='userinfo',
            name='subdivision_id',
        ),
    ]
