# Generated by Django 3.2.21 on 2023-09-25 14:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='DishWeightName',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('weight_name', models.CharField(max_length=50)),
            ],
            options={
                'verbose_name': 'Dish weight name',
                'verbose_name_plural': 'Dish weight names',
                'db_table': 'dish_weight_name',
            },
        ),
        migrations.CreateModel(
            name='DishWeek',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dish_date', models.DateField()),
                ('dish_name', models.CharField(max_length=255)),
                ('dish_weight', models.PositiveSmallIntegerField()),
                ('eating', models.CharField(max_length=255)),
                ('dish_weight_id', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='dish.dishweightname')),
            ],
            options={
                'verbose_name': 'Dish week',
                'verbose_name_plural': 'Dish weeks',
                'db_table': 'dish_week',
            },
        ),
    ]
