# Generated by Django 3.2.21 on 2023-09-25 14:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='SchoolMS',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sSchool_name', models.CharField(max_length=155)),
                ('sSchool_address', models.CharField(max_length=155)),
                ('sSchool_direct', models.CharField(max_length=155)),
                ('sSchool_language', models.CharField(max_length=155)),
                ('isSchool', models.PositiveSmallIntegerField()),
                ('sCommentary', models.CharField(max_length=255, null=True)),
                ('sBin', models.CharField(max_length=12)),
            ],
            options={
                'verbose_name': 'SchoolMs',
                'verbose_name_plural': 'SchoolsMs',
                'db_table': 'spr_School',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='School',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sSchool_logo', models.ImageField(null=True, upload_to='school/logo/')),
                ('sSchool_name', models.CharField(max_length=155)),
                ('sSchool_address', models.CharField(max_length=155)),
                ('sSchool_direct', models.CharField(max_length=155)),
                ('sSchool_language', models.CharField(max_length=155)),
                ('isSchool', models.PositiveSmallIntegerField()),
                ('sCommentary', models.CharField(max_length=255, null=True)),
                ('sBin', models.CharField(max_length=12)),
            ],
            options={
                'verbose_name': 'School',
                'verbose_name_plural': 'Schools',
                'db_table': 'school',
            },
        ),
        migrations.CreateModel(
            name='SchoolRequisites',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bank_name', models.CharField(max_length=155)),
                ('bank_address', models.CharField(max_length=155)),
                ('bank_bik', models.CharField(max_length=9)),
                ('bank_iik', models.CharField(max_length=20)),
                ('bank_kbe', models.CharField(max_length=20)),
                ('bank_rs', models.CharField(max_length=20)),
                ('bank_ks', models.CharField(max_length=20)),
                ('bank_bin', models.CharField(max_length=12)),
                ('school', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='school.school')),
            ],
            options={
                'verbose_name': 'SchoolRequisite',
                'verbose_name_plural': 'SchoolRequisites',
                'db_table': 'schoolRequisites',
            },
        ),
        migrations.CreateModel(
            name='Class',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('class_num', models.IntegerField()),
                ('class_liter', models.CharField(max_length=1)),
                ('commentary', models.CharField(max_length=255, null=True)),
                ('isActive', models.BooleanField(default=True)),
                ('isGraduated', models.BooleanField(default=False)),
                ('max_class_num', models.PositiveIntegerField(default=11)),
                ('modified', models.DateTimeField(auto_now=True)),
                ('school', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='school.school')),
            ],
            options={
                'verbose_name': 'Class',
                'verbose_name_plural': 'Classes',
                'db_table': 'class',
            },
        ),
    ]
