# Generated by Django 3.2.21 on 2023-09-25 14:01

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='BankMS',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('account', models.CharField(max_length=255)),
                ('name', models.CharField(max_length=255)),
                ('bik', models.CharField(max_length=255)),
            ],
            options={
                'db_table': 'spr_Bank',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='ClassMS',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('class_num', models.CharField(max_length=255, null=True)),
                ('class_liter', models.CharField(max_length=5, null=True)),
                ('commentary', models.CharField(max_length=255, null=True)),
                ('isActive', models.BooleanField(default=True)),
            ],
            options={
                'db_table': 'spr_Classes',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='CompanyMS',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('address', models.CharField(max_length=255, null=True)),
                ('name', models.CharField(max_length=255, null=True)),
                ('bank', models.CharField(max_length=255, null=True)),
                ('bik', models.CharField(max_length=255, null=True)),
                ('bin', models.CharField(max_length=255, null=True)),
                ('iik', models.CharField(max_length=255, null=True)),
            ],
            options={
                'db_table': 'spr_Company',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='ContractDiscountMS',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('DiscountSum', models.DecimalField(decimal_places=2, max_digits=10, null=True)),
            ],
            options={
                'db_table': 't_ContractDiscount',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='ContractDriverMonthPayMS',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('PayDateM', models.DateField(auto_now=True, null=True)),
                ('MonthAmount', models.DecimalField(decimal_places=2, max_digits=10, null=True)),
                ('MonthAmountDisc', models.DecimalField(decimal_places=2, max_digits=10, null=True)),
                ('IsClosedContract', models.BooleanField(default=False)),
                ('DateClosed', models.DateField(null=True)),
                ('QuarterDig', models.PositiveSmallIntegerField(null=True)),
            ],
            options={
                'db_table': 't_ContractMonthPayDriver',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='ContractDriverMS',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ContractDate', models.DateField(auto_now=True, null=True)),
                ('ContractDateClose', models.DateField(auto_now=True, null=True)),
                ('ContractNum', models.CharField(max_length=255)),
                ('ContractAmount', models.DecimalField(decimal_places=2, max_digits=10, null=True)),
                ('ContractAmountDis', models.DecimalField(decimal_places=2, max_digits=10, null=True)),
                ('signature_uid', models.CharField(max_length=255, null=True)),
            ],
            options={
                'db_table': 't_ContractDriver',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='ContractFoodDiscountMS',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('DiscountSum', models.DecimalField(decimal_places=2, max_digits=10, null=True)),
            ],
            options={
                'db_table': 't_ContractFoodDiscount',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='ContractFoodMonthPayMS',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('PayDateM', models.DateField(auto_now=True, null=True)),
                ('MonthAmount', models.DecimalField(decimal_places=2, max_digits=10, null=True)),
                ('MonthSum', models.DecimalField(decimal_places=2, max_digits=10, null=True)),
                ('IsClosedContract', models.BooleanField(default=False)),
                ('DateClosed', models.DateField(null=True)),
            ],
            options={
                'db_table': 't_ContractMonthPayFood',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='ContractFoodMS',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ContractDate', models.DateField(auto_now=True, null=True)),
                ('ContractDateClose', models.DateField(auto_now=True, null=True)),
                ('ContractNum', models.CharField(max_length=255)),
                ('ContractAmount', models.DecimalField(decimal_places=2, max_digits=10, null=True)),
                ('ContractSum', models.DecimalField(decimal_places=2, max_digits=10, null=True)),
                ('signature_uid', models.CharField(max_length=255, null=True)),
                ('Comment', models.CharField(max_length=255, null=True)),
            ],
            options={
                'db_table': 't_ContractFood',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='ContractMonthPayMS',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('PayDateM', models.DateField(auto_now=True, null=True)),
                ('MonthAmount', models.DecimalField(decimal_places=2, max_digits=10, null=True)),
                ('MonthSum', models.DecimalField(decimal_places=2, max_digits=10, null=True)),
                ('IsClosedContract', models.BooleanField(default=False)),
                ('DateClosed', models.DateField(null=True)),
                ('QuarterDig', models.PositiveSmallIntegerField(null=True)),
            ],
            options={
                'db_table': 't_ContractMonthPay',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='ContractMS',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ContractDate', models.DateField(auto_now=True, null=True)),
                ('ContractDateClose', models.DateField(null=True)),
                ('ContractNum', models.CharField(max_length=255, null=True)),
                ('ContractAmount', models.DecimalField(decimal_places=2, max_digits=10, null=True)),
                ('ContractSum', models.DecimalField(decimal_places=2, max_digits=10, null=True)),
                ('Contribution', models.PositiveSmallIntegerField(null=True)),
                ('ContSum', models.DecimalField(decimal_places=2, max_digits=10, null=True)),
                ('signature_uid', models.CharField(max_length=255, null=True)),
            ],
            options={
                'db_table': 't_Contract',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='ContractStatusMS',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sStatusName', models.CharField(max_length=255, null=True)),
            ],
            options={
                'db_table': 'spr_Status',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='DiscountMS',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sDiscountName', models.CharField(max_length=255, null=True)),
                ('iDiscountPercent', models.PositiveIntegerField(null=True)),
                ('sCommentary', models.CharField(max_length=255, null=True)),
                ('bIsActive', models.BooleanField(default=True)),
            ],
            options={
                'db_table': 'spr_Discount',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='DiscountTypeMS',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sDiscountType', models.CharField(max_length=255, null=True)),
                ('sCommentary', models.CharField(max_length=255, null=True)),
            ],
            options={
                'db_table': 'spr_DiscountType',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='EduYearMS',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sEduYear', models.CharField(max_length=255, null=True)),
                ('isActive', models.BooleanField(default=True)),
            ],
            options={
                'db_table': 'spr_EduYear',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='ParentMS',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=255)),
                ('address', models.CharField(max_length=255, null=True)),
                ('contacts', models.CharField(max_length=255, null=True)),
                ('email', models.EmailField(max_length=254, null=True)),
                ('iin', models.CharField(max_length=12, null=True)),
                ('is_teacher', models.BooleanField(default=False)),
                ('num_of_doc', models.CharField(max_length=255, null=True)),
                ('issued_by', models.CharField(max_length=255, null=True)),
                ('issue_date', models.DateField(null=True)),
                ('phone', models.CharField(max_length=20, null=True)),
                ('work_place', models.CharField(max_length=255, null=True)),
                ('work_position', models.CharField(max_length=255, null=True)),
                ('is_deleted', models.BooleanField(default=False)),
            ],
            options={
                'db_table': 't_Parents',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='PaymentTypeMS',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sPaymentType', models.CharField(max_length=255, null=True)),
            ],
            options={
                'db_table': 'spr_PaymentType',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='StudentMS',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('birthday', models.DateField()),
                ('full_name', models.CharField(max_length=255)),
                ('iin', models.CharField(max_length=12, null=True)),
                ('leave', models.DateField(null=True)),
                ('reason_leave', models.CharField(max_length=255, null=True)),
                ('sex', models.PositiveSmallIntegerField(null=True)),
                ('email', models.EmailField(max_length=254, null=True)),
                ('phone', models.CharField(max_length=20, null=True)),
            ],
            options={
                'db_table': 't_Students',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='TransactionDriverMS',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Amount', models.DecimalField(decimal_places=2, max_digits=10, null=True)),
                ('Description', models.CharField(max_length=255, null=True)),
                ('TransactionDate', models.DateTimeField(auto_now=True, null=True)),
            ],
            options={
                'db_table': 't_TransactionDrive',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='TransactionFoodMS',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10, null=True)),
                ('description', models.CharField(max_length=255, null=True)),
                ('trans_date', models.DateTimeField(auto_now=True, null=True)),
                ('Akt_status', models.CharField(max_length=255, null=True)),
            ],
            options={
                'db_table': 't_TransactionFood',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='TransactionMS',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10, null=True)),
                ('description', models.CharField(max_length=255, null=True)),
                ('is_increase', models.BooleanField(default=True)),
                ('name', models.CharField(max_length=255, null=True)),
                ('contribution', models.BooleanField(default=False)),
                ('trans_date', models.DateTimeField(auto_now=True, null=True)),
                ('is_dop_contr', models.BooleanField(default=False, null=True)),
                ('dop_contr_date', models.DateTimeField(null=True)),
            ],
            options={
                'db_table': 't_Transaction',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='ContractFileUser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('contractNum', models.CharField(max_length=255, null=True)),
                ('file', models.FileField(upload_to='contract/files/')),
                ('date', models.DateTimeField(auto_now_add=True, null=True)),
            ],
            options={
                'db_table': 'ContractFileUser',
            },
        ),
        migrations.CreateModel(
            name='MarkedUpContractTemplate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(upload_to='templates/contracts/markedup/')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Время создания')),
                ('changed_at', models.DateTimeField(auto_now=True, verbose_name='Время изменения')),
                ('name', models.CharField(max_length=200, verbose_name='Название размеченного шаблона')),
            ],
            options={
                'db_table': 'marked_up_contract_template',
            },
        ),
        migrations.CreateModel(
            name='RawContractTemplate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(upload_to='templates/contracts/raw/', validators=[django.core.validators.FileExtensionValidator(['doc', 'docx'])])),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Время создания')),
                ('changed_at', models.DateTimeField(auto_now=True, verbose_name='Время изменения')),
                ('name', models.CharField(max_length=200, verbose_name='Название шаблона')),
            ],
            options={
                'db_table': 'raw_contract_template',
            },
        ),
    ]
