# Generated by Django 3.2.21 on 2023-09-25 14:01

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('contract', '0001_initial'),
        ('school', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='rawcontracttemplate',
            name='school',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='raw_contract_templates', to='school.school'),
        ),
        migrations.AddField(
            model_name='markedupcontracttemplate',
            name='raw_contract_template',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='marked_up_contracts', to='contract.rawcontracttemplate'),
        ),
        migrations.AddField(
            model_name='markedupcontracttemplate',
            name='school',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='marked_up_contracts', to='school.school'),
        ),
        migrations.AddField(
            model_name='contractfileuser',
            name='user',
            field=models.ForeignKey(db_column='user', null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
    ]
