# Generated by Django 3.2.21 on 2023-09-29 11:58

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('contract', '0002_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ContractDopMS',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10, null=True)),
                ('description', models.CharField(max_length=255, null=True)),
                ('is_increase', models.BooleanField(default=False)),
                ('dop_contr_date', models.DateField(null=True)),
            ],
            options={
                'db_table': 't_ContractDop',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='ContractDopFileUser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('contractNum', models.CharField(max_length=255, null=True)),
                ('file', models.FileField(upload_to='contract_dop/files/')),
                ('date', models.DateTimeField(auto_now_add=True, null=True)),
                ('user', models.ForeignKey(db_column='user', null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'ContractDopFileUser',
            },
        ),
    ]
