# Generated by Django 3.2.25 on 2025-09-10 10:38

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('contract', '0003_contractdopfileuser_contractdopms'),
    ]

    operations = [
        migrations.CreateModel(
            name='ContractSignature',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('contract_num', models.CharField(help_text='Номер контракта из ContractMS.ContractNum', max_length=255, verbose_name='Номер контракта')),
                ('cms_signature', models.TextField(help_text='Подпись в формате CMS', verbose_name='CMS подпись')),
                ('signed_data', models.TextField(help_text='Base64 данные которые были подписаны', verbose_name='Подписанные данные')),
                ('document_hash', models.CharField(blank=True, help_text='SHA256 хэш документа на момент подписания', max_length=64, null=True, verbose_name='Хэш документа')),
                ('signer_iin', models.CharField(help_text='ИИН извлеченный из сертификата', max_length=12, verbose_name='ИИН подписанта')),
                ('certificate_info', models.JSONField(default=dict, help_text='Данные сертификата из NCANode ответа', verbose_name='Информация о сертификате')),
                ('is_valid', models.BooleanField(default=True, help_text='Результат валидации подписи', verbose_name='Подпись валидна')),
                ('signed_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата подписания')),
                ('verified_at', models.DateTimeField(auto_now=True, verbose_name='Дата последней проверки')),
                ('signature_uid', models.UUIDField(default=uuid.uuid4, editable=False, unique=True, verbose_name='Уникальный ID подписи')),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_signatures', to=settings.AUTH_USER_MODEL, verbose_name='Создано пользователем')),
            ],
            options={
                'verbose_name': 'Подпись контракта',
                'verbose_name_plural': 'Подписи контрактов',
                'db_table': 'contract_signatures',
                'ordering': ['-signed_at'],
            },
        ),
        migrations.AddIndex(
            model_name='contractsignature',
            index=models.Index(fields=['contract_num'], name='contract_si_contrac_b3ea2e_idx'),
        ),
        migrations.AddIndex(
            model_name='contractsignature',
            index=models.Index(fields=['signer_iin'], name='contract_si_signer__e4ab1f_idx'),
        ),
        migrations.AddIndex(
            model_name='contractsignature',
            index=models.Index(fields=['is_valid'], name='contract_si_is_vali_c830f9_idx'),
        ),
    ]
