# Generated by Django 3.2.21 on 2023-09-25 14:01

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Statement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=255)),
                ('iin', models.CharField(max_length=12)),
                ('birthday', models.DateField()),
                ('num_of_doc', models.CharField(max_length=50)),
                ('is_nutrition', models.BooleanField(default=False)),
                ('is_transport', models.BooleanField(default=False)),
                ('student_class', models.CharField(max_length=255, null=True)),
                ('student_position', models.CharField(max_length=255, null=True)),
                ('commentary', models.CharField(max_length=255, null=True)),
                ('student_image', models.ImageField(null=True, upload_to='statement/stud_images/')),
                ('parent', models.ForeignKey(blank=True, db_column='parent', null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Statement',
                'verbose_name_plural': 'Statements',
                'db_table': 'statement',
            },
        ),
        migrations.CreateModel(
            name='StatementDocFile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(blank=True, null=True, upload_to='statement/doc_files/', validators=[django.core.validators.FileExtensionValidator(['pdf', 'doc', 'docx', 'jpg', 'jpeg', 'png'])])),
                ('statement', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='statement_files', to='statement.statement')),
            ],
            options={
                'verbose_name': 'Statement doc file',
                'verbose_name_plural': 'Statement doc files',
                'db_table': 'statement_doc_file',
            },
        ),
    ]
