# Generated by Django 3.2.21 on 2023-09-25 14:01

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import phonenumber_field.modelfields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('school', '0002_class_teacher'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('id_from_ms', models.IntegerField(blank=True, null=True, unique=True)),
                ('photo_avatar', models.ImageField(null=True, upload_to='student/avatar/')),
                ('birthday', models.DateField()),
                ('full_name', models.CharField(max_length=150)),
                ('iin', models.CharField(max_length=12, unique=True)),
                ('leave', models.DateField(null=True)),
                ('reason_leave', models.CharField(max_length=255, null=True)),
                ('sex', models.SmallIntegerField(null=True)),
                ('email', models.EmailField(max_length=254, null=True)),
                ('phone', phonenumber_field.modelfields.PhoneNumberField(max_length=128, null=True, region=None)),
                ('parent', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='main_parent', to=settings.AUTH_USER_MODEL)),
                ('stud_class', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='student_class', to='school.class')),
            ],
            options={
                'verbose_name': 'Student',
                'verbose_name_plural': 'Students',
                'db_table': 'student',
            },
        ),
    ]
