# Generated by Django 3.2.25 on 2025-10-02 09:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('applications', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Campus',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True, verbose_name='Название кампуса')),
                ('description', models.TextField(blank=True, null=True, verbose_name='Описание')),
                ('is_active', models.BooleanField(default=True, verbose_name='Активен')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Кампус',
                'verbose_name_plural': 'Кампусы',
                'db_table': 'campus',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Subdivision',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Название подразделения')),
                ('level', models.IntegerField(help_text='1 для subdivision1, 2 для subdivision2', verbose_name='Уровень')),
                ('is_active', models.BooleanField(default=True, verbose_name='Активен')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('campus', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='subdivisions', to='applications.campus', verbose_name='Кампус')),
                ('parent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='children', to='applications.subdivision', verbose_name='Родительское подразделение')),
            ],
            options={
                'verbose_name': 'Подразделение',
                'verbose_name_plural': 'Подразделения',
                'db_table': 'subdivision',
                'ordering': ['level', 'name'],
                'unique_together': {('name', 'level', 'campus')},
            },
        ),
        migrations.AlterField(
            model_name='application',
            name='campus',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='application', to='applications.campus', verbose_name='Кампус'),
        ),
        migrations.AlterField(
            model_name='application',
            name='subdivision1',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='application_sub1', to='applications.subdivision', verbose_name='Подразделение 1'),
        ),
        migrations.AlterField(
            model_name='application',
            name='subdivision2',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='application_sub2', to='applications.subdivision', verbose_name='Подразделение 2'),
        ),
        migrations.AlterField(
            model_name='serviceprovider',
            name='campus',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='service_providers', to='applications.campus', verbose_name='Кампус'),
        ),
        migrations.AlterField(
            model_name='serviceprovider',
            name='subdivision1',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='service_providers_sub1', to='applications.subdivision', verbose_name='Подразделение 1'),
        ),
        migrations.AlterField(
            model_name='serviceprovider',
            name='subdivision2',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='service_providers_sub2', to='applications.subdivision', verbose_name='Подразделение 2'),
        ),
    ]
