# Generated by Django 3.2.25 on 2025-10-03 06:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('applications', '0002_auto_20251002_1409'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='subdivision',
            unique_together=None,
        ),
        migrations.RemoveField(
            model_name='subdivision',
            name='campus',
        ),
        migrations.RemoveField(
            model_name='subdivision',
            name='parent',
        ),
        migrations.AlterField(
            model_name='application',
            name='campus',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Кампус'),
        ),
        migrations.AlterField(
            model_name='application',
            name='subdivision1',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Подразделение 1'),
        ),
        migrations.AlterField(
            model_name='application',
            name='subdivision2',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Подразделение 2'),
        ),
        migrations.AlterField(
            model_name='serviceprovider',
            name='campus',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Кампус'),
        ),
        migrations.AlterField(
            model_name='serviceprovider',
            name='subdivision1',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Подразделение 1'),
        ),
        migrations.AlterField(
            model_name='serviceprovider',
            name='subdivision2',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Подразделение 2'),
        ),
        migrations.DeleteModel(
            name='Campus',
        ),
        migrations.DeleteModel(
            name='Subdivision',
        ),
    ]
