from django.db.models import TextChoices

default_app_config = 'apps.contract.apps.ContractConfig'

class ContractVariable(TextChoices):
    contract_num = '{ContractNum}', 'Номер контракта'
    contract_year = '{ContractYear}', 'Год заключения контракта'
    contract_date = '{ContractDate}', 'Дата заключения контракта (полная)'
    contract_day = '{ContractDay}', 'День месяца заключения контракта'
    contract_month_rus = '{ContractMonthRUS}', 'Месяц заключения контракта на русском '
    contract_month_kaz = '{ContractMonthKAZ}', 'Месяц заключения контракта на казахском'
    contract_month_eng = '{ContractMonthENG}', 'Месяц заключения контракта на английском'
    edu_year = '{EduYear}', 'Учебный год'
    parent_fullname = '{ParentFullName}', 'ФИО родителей'
    student_fullname = '{StudentFullName}', 'ФИО обучающегося'
    contract_amount = '{ContractAmount}', 'Стоимость (в цифрах)'
    contract_amount_words = '{ContractAmountWords}', 'Стоимость (прописью) на русском'
    contract_amount_words_kaz = '{ContractAmountWordsKaz}', 'Стоимость (прописью) на казахском'
    contract_amount_words_eng = '{ContractAmountWordsEng}', 'Стоимость (прописью) на английском'
    student_iin = '{StudentIIN}', 'ИИН обучающегося'
    student_address = '{StudentAddress}', 'Адрес обучающегося'
    student_phone_number = '{StudentPhoneNumber}', 'Номер телефона обучающегося'
    parent_address = '{ParentAddress}', 'Адрес родителей'
    parent_phone_number = '{ParentPhoneNumber}', 'Номер телефона родителей'
    parent_iin = '{ParentIIN}', 'ИИН родителей'
    parent_passport = '{ParentPassport}', 'Данные документа, удостоверяющего личность родителей на русском'
    parent_passport_kaz = '{ParentPassportKAZ}', 'Данные документа, удостоверяющего личность родителей на казахском'
    parent_passport_eng = '{ParentPassportENG}', 'Данные документа, удостоверяющего личность родителей на английском'
    customtable_monthpay = '{customtable_monthpay}', 'Оплата помесячная'
    customtable_quarterpay = '{customtable_quarterpay}', 'Оплата поквартальная'
