# Generated by Django 3.2.21 on 2023-09-25 14:01

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='KaspiTransactionMS',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('clazz', models.CharField(blank=True, max_length=255, null=True)),
                ('transaction_id', models.IntegerField()),
                ('txn_id', models.IntegerField()),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('sum', models.IntegerField()),
            ],
            options={
                'verbose_name': 'Kaspi Transaction',
                'verbose_name_plural': 'Kaspi Transactions',
                'db_table': 'kaspi_transactions',
                'managed': False,
            },
        ),
    ]
